[package]
name = "partiql-catalog"
description = "PartiQL Catalog Definitions"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
license = "Apache-2.0"
readme = "../README.md"
keywords = ["sql", "parser", "query", "compilers", "interpreters"]
categories = ["database", "compilers"]
exclude = [
  "**/.git/**",
  "**/.github/**",
  "**/.travis.yml",
  "**/.appveyor.yml",
]
version.workspace = true
edition.workspace = true

[lib]
bench = false

[dependencies]
partiql-value = { path = "../partiql-value", version = "0.5.*" }
partiql-parser = { path = "../partiql-parser", version = "0.5.*" }
partiql-logical = { path = "../partiql-logical", version = "0.5.*" }
partiql-types = { path = "../partiql-types", version = "0.5.*" }

thiserror = "1.0"
ordered-float = "3.*"
itertools = "0.10.*"
unicase = "2.6"

[dev-dependencies]
criterion = "0.4"
