coverage:
  status:
    project:
      default:
        target: 80%
        threshold: 5%
    patch:
      default:
        target: 85%
        threshold: 5%

ignore:
  # Ignore the Pest generated code until we have a better way to test
  # and target coverage for it
  - "partiql-parser/src/peg/gen.rs"
