[package]
name = "partiql-parser-fuzz"
authors.workspace = true
homepage.workspace = true
repository.workspace = true
publish = false
license = "Apache-2.0"
version.workspace = true
edition.workspace = true

[package.metadata]
cargo-fuzz = true

[dependencies]
libfuzzer-sys = "0.4"

[dependencies.partiql-parser]
path = ".."

# Prevent this from interfering with workspaces
[workspace]
members = ["."]

[[bin]]
name = "fuzz_parse_string"
path = "fuzz_targets/fuzz_parse_string.rs"
test = false
doc = false
