[package]
name = "partiql-jni"
version = "0.14.0"
edition = "2021"
license = "Apache-2.0"
authors = ["PartiQL Team <partiql-team@amazon.com>"]
homepage = "https://github.com/partiql/partiql-lang-rust"
repository = "https://github.com/partiql/partiql-lang-rust"

[lib]
crate-type = ["cdylib"]  # Dynamic library for JNI

[dependencies]
partiql-eval = { path = "../../partiql-eval", version = "0.14.*" }
partiql-parser = { path = "../../partiql-parser", version = "0.14.*" }
partiql-logical-planner = { path = "../../partiql-logical-planner", version = "0.14.*" }
partiql-catalog = { path = "../../partiql-catalog", version = "0.14.*" }
partiql-value = { path = "../../partiql-value", version = "0.14.*" }
partiql-common = { path = "../../partiql-common", version = "0.14.*" }
jni = "0.21"
dashmap = "6"
once_cell = "1"

[build-dependencies]
